### ISSUE TITLE
Vector Certificate Download

### ISSUE THREAD

**Issue by F4310** [Hamlet3000/cronVec#1]
Please, can you help me?

Downloading Vector certificate from Anki...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xffff8261fee0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/0070527b (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff8261fee0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/configure/__main__.py", line 322, in <module>
    main(Api())
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/configure/__main__.py", line 302, in main
    cert, serial = get_cert(args.serial)
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/configure/__main__.py", line 101, in get_cert
    r = requests.get('https://session-certs.token.global.anki-services.com/vic/{}'.format(serial))
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/0070527b (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff8261fee0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno -2] Name or service not known)"))

**Comment by Hamlet3000** [comment]
Is the Python SDK installed correctly? Are other Vector SDK scripts running correctly, such as 01_hello_world.py? (https://github.com/anki/vector-python-sdk/tree/master/examples/tutorials)

It seems that the certificate could not be downloaded. It could be because all DDL servers are down.

**Comment by F4310** [comment]
Yes, correctly installed. I think is because DDL servers até down. 
I will wait ......
Thank you for The awnser.
